packages: []
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@revisium/revo-agent-runtime@0.2.0-alpha.0'
  - '@revisium/revo-pipeline@0.2.0-alpha.3'
  - '@revisium/revo-scripts@0.1.0-alpha.1'
