sonar.projectKey=revisium_revo-run
sonar.organization=revisium
sonar.projectName=revo-run
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.typescript.tsconfigPaths=tsconfig.json

sonar.exclusions=dist/**,node_modules/**,**/generated/**
sonar.coverage.exclusions=src/**
sonar.cpd.exclusions=**/generated/**
