import {
  agentBinding,
  completeNode,
  end,
  executionPlan,
  expectEvent,
  expectJsonOutput,
  expectNodeInput,
  expectNodeExecutions,
  expectRunStatus,
  failNode,
  fromMapItem,
  fromRunInput,
  routeOutcomes,
  scenario,
  sequence,
  startRun,
  task,
  type RunScenario,
} from '../../dsl/run-scenario.js';

export const mapScenarios: readonly RunScenario[] = [
  scenario({
    capability: 'map',
    name: 'maps a bounded task over dynamically supplied entities',
    blockedBy: 'runRuntime',
    plan: executionPlan(
      sequence(
        {
          kind: 'map',
          key: 'repositories',
          items: fromRunInput('/repositories'),
          itemKeyPath: '/id',
          maximumItems: 100,
          concurrency: 10,
          failure: { kind: 'failFast', remaining: 'cancel' },
          body: task('review', { input: { repository: fromMapItem('') } }),
        },
        end('succeeded'),
      ),
      { bindings: [agentBinding('repositories/review', 'reviewer')] },
    ),
    steps: [
      startRun({ repositories: [{ id: 'a' }, { id: 'b' }, { id: 'c' }] }),
      expectNodeExecutions(
        'main/repositories[a]/review',
        'main/repositories[b]/review',
        'main/repositories[c]/review',
      ),
      expectNodeInput('main/repositories[a]/review', { repository: { id: 'a' } }),
      completeNode('main/repositories[a]/review'),
      completeNode('main/repositories[b]/review'),
      completeNode('main/repositories[c]/review'),
      expectRunStatus('succeeded'),
    ],
  }),
  scenario({
    capability: 'map',
    name: 'completes an empty map without scheduling child executions',
    blockedBy: 'runRuntime',
    plan: executionPlan(
      sequence(
        {
          kind: 'map',
          key: 'repositories',
          items: fromRunInput('/repositories'),
          itemKeyPath: '/id',
          maximumItems: 100,
          concurrency: 10,
          failure: { kind: 'failFast', remaining: 'cancel' },
          body: task('review'),
        },
        end('succeeded'),
      ),
      { bindings: [agentBinding('repositories/review', 'reviewer')] },
    ),
    steps: [
      startRun({ repositories: [] }),
      { kind: 'expectNoNodeExecution', path: 'main/repositories[*]/review' },
      expectRunStatus('succeeded'),
    ],
  }),
  scenario({
    capability: 'map',
    name: 'encodes data-controlled map item keys in runtime paths',
    blockedBy: 'runRuntime',
    plan: executionPlan(
      sequence(
        {
          kind: 'map',
          key: 'repositories',
          items: fromRunInput('/repositories'),
          itemKeyPath: '/id',
          maximumItems: 10,
          concurrency: 2,
          failure: { kind: 'failFast', remaining: 'cancel' },
          body: task('review'),
        },
        end('succeeded'),
      ),
      { bindings: [agentBinding('repositories/review', 'reviewer')] },
    ),
    steps: [
      startRun({ repositories: [{ id: 'a]/x' }] }),
      expectNodeExecutions('main/repositories[a%5D%2Fx]/review'),
      completeNode('main/repositories[a%5D%2Fx]/review'),
      expectRunStatus('succeeded'),
    ],
  }),
  scenario({
    capability: 'map',
    name: 'rejects map input that exceeds its declared item bound',
    blockedBy: 'runRuntime',
    plan: executionPlan(
      routeOutcomes(
        {
          kind: 'map',
          key: 'repositories',
          items: fromRunInput('/repositories'),
          itemKeyPath: '/id',
          maximumItems: 2,
          concurrency: 2,
          failure: { kind: 'failFast', remaining: 'cancel' },
          body: task('review'),
        },
        { completed: end('succeeded'), limitExceeded: end('failed') },
      ),
      { bindings: [agentBinding('repositories/review', 'reviewer')] },
    ),
    steps: [
      startRun({ repositories: [{ id: 'a' }, { id: 'b' }, { id: 'c' }] }),
      expectEvent('map.limitExceeded', { path: 'main/repositories' }),
      { kind: 'expectNoNodeExecution', path: 'main/repositories[*]/review' },
      expectRunStatus('failed'),
    ],
  }),
  scenario({
    capability: 'map',
    name: 'cancels remaining map items after one item fails in fail-fast mode',
    blockedBy: 'runRuntime',
    plan: executionPlan(
      routeOutcomes(
        {
          kind: 'map',
          key: 'repositories',
          items: fromRunInput('/repositories'),
          itemKeyPath: '/id',
          maximumItems: 100,
          concurrency: 3,
          failure: { kind: 'failFast', remaining: 'cancel' },
          body: task('review'),
        },
        { completed: end('succeeded'), failed: end('failed') },
      ),
      { bindings: [agentBinding('repositories/review', 'reviewer')] },
    ),
    steps: [
      startRun({ repositories: [{ id: 'a' }, { id: 'b' }, { id: 'c' }] }),
      failNode('main/repositories[a]/review', 'review_failed'),
      expectEvent('nodeExecution.cancelled', { path: 'main/repositories[b]/review' }),
      expectEvent('nodeExecution.cancelled', { path: 'main/repositories[c]/review' }),
      expectRunStatus('failed'),
    ],
  }),
  scenario({
    capability: 'map',
    name: 'enforces map-local concurrency independently of item count',
    blockedBy: 'runRuntime',
    plan: executionPlan(
      sequence(
        {
          kind: 'map',
          key: 'repositories',
          items: fromRunInput('/repositories'),
          itemKeyPath: '/id',
          maximumItems: 100,
          concurrency: 2,
          failure: { kind: 'collect' },
          body: task('review'),
        },
        end('succeeded'),
      ),
      { bindings: [agentBinding('repositories/review', 'reviewer')] },
    ),
    steps: [
      startRun({ repositories: [{ id: 'a' }, { id: 'b' }, { id: 'c' }] }),
      { kind: 'expectMaximumActiveExecutions', count: 2 },
      completeNode('main/repositories[a]/review'),
      expectNodeExecutions('main/repositories[c]/review'),
      completeNode('main/repositories[b]/review'),
      completeNode('main/repositories[c]/review'),
      expectRunStatus('succeeded'),
    ],
  }),
  scenario({
    capability: 'map',
    name: 'collects failed map items and exposes a deterministic aggregate outcome',
    blockedBy: 'runRuntime',
    plan: executionPlan(
      routeOutcomes(
        {
          kind: 'map',
          key: 'repositories',
          items: fromRunInput('/repositories'),
          itemKeyPath: '/id',
          maximumItems: 10,
          concurrency: 2,
          failure: { kind: 'collect' },
          body: task('review'),
        },
        {
          completed: end('succeeded'),
          completedWithErrors: end('failed', { outcome: 'partial-failure' }),
        },
      ),
      { bindings: [agentBinding('repositories/review', 'reviewer')] },
    ),
    steps: [
      startRun({ repositories: [{ id: 'a' }, { id: 'b' }] }),
      failNode('main/repositories[a]/review', 'review_failed'),
      completeNode('main/repositories[b]/review'),
      expectJsonOutput('main/repositories', 'summary', {
        totalItems: 2,
        completedItems: 1,
        failedItems: 1,
        failures: [{ itemKey: 'a', outcome: 'failed' }],
      }),
      expectRunStatus('failed'),
    ],
  }),
];
