export type RunFaultCode =
  | 'INVALID_INPUT'
  | 'NOT_FOUND'
  | 'INVALID_STATE'
  | 'STALE_ACTIVATION'
  | 'REVISION_CONFLICT'
  | 'STALE_FENCE'
  | 'PLAN_UNAVAILABLE'
  | 'PLAN_MISMATCH'
  | 'EXECUTOR_UNAVAILABLE'
  | 'EXECUTOR_MISMATCH'
  | 'UNKNOWN_OUTCOME'
  | 'CANCELLED';
