export type RunStoreNonRenewIncumbentOperation =
  | 'start'
  | 'pre_start_failure'
  | 'pre_start_cancellation'
  | 'direct_success'
  | 'direct_failure'
  | 'direct_cancellation'
  | 'direct_unknown'
  | 'begin_reconciliation'
  | 'late_success'
  | 'late_failure'
  | 'late_cancellation'
  | 'reconciled_running'
  | 'reconciled_unknown'
  | 'reconciled_success'
  | 'reconciled_failure'
  | 'reconciled_cancellation';
